### ISSUE TITLE
Context menu position

### ISSUE THREAD

**Issue by cprcrack** [0xdevalias/chrome-NewWindowWithTabsToRight#2]
Can the context menu option "open tabs to the right in new window" be placed in the regular Chrome context menu that is displayed when you right click on any tab title? I mean the same menu where "Close tabs to the right" is displayed by default by Chrome.

**Comment by 0xdevalias** [comment]
Unfortunately not. Chrome restricts the ability for extensions to modify any of the 'standard UI' features, which include that menu. I would have loved to be able to put it there too.
